    #############################################################################
    #############################################################################
    ######### Managed by Terraform, not safe to change ##########################
    #############################################################################
    #############################################################################
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autoscaler
  namespace: kube-system
spec:
  values:
    autoDiscovery:
      clusterName: nacho-test-eks-1
    awsRegion: eu-central-1
    rbac:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::492737776546:role/nacho-test-cluster-autoscaler
